services:
    # db:
    #   image: mysql:latest
    #   container_name: mysql_container
    #   environment:
    #     MYSQL_ROOT_PASSWORD: ${PMA_ROOT_PASSWORD}
    #     MYSQL_DATABASE: tmp_db
    #   ports:
    #     - "${DISCORD_EVO_DB}:${DISCORD_EVO_DB}"
    #   volumes:
    #     - mysql_data:/var/lib/mysql
    #     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin:latest
    #   container_name: phpmyadmin_container
    #   environment:
    #     PMA_HOST: db
    #     PMA_PORT: ${DISCORD_EVO_DB}
    #     MYSQL_ROOT_PASSWORD: ${PMA_ROOT_PASSWORD}
    #   ports:
    #     - "${DISCORD_EVO_PMA}:80"
    #   depends_on:
    #     - db

    server:
        build:
            context: .
        container_name: server_container
        volumes:
            - .:/app
            # - ./backup:/backup
        ports:
            - "${DISCORD_EVO_API}:${DISCORD_EVO_API}"
        # depends_on:
        #     - db
# volumes:
#     mysql_data:
